/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AwesomeCounter {
        "max": number;
        "min": number;
        "start": number;
        "step": number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAwesomeCounterElement extends Components.AwesomeCounter, HTMLStencilElement {
    }
    var HTMLAwesomeCounterElement: {
        prototype: HTMLAwesomeCounterElement;
        new (): HTMLAwesomeCounterElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "awesome-counter": HTMLAwesomeCounterElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AwesomeCounter {
        "max"?: number;
        "min"?: number;
        "onCounterUpdate"?: (event: CustomEvent<any>) => void;
        "start"?: number;
        "step"?: number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "awesome-counter": AwesomeCounter;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "awesome-counter": LocalJSX.AwesomeCounter & JSXBase.HTMLAttributes<HTMLAwesomeCounterElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
